ARG VERSION=latest

FROM mcr.microsoft.com/devcontainers/base:ubuntu

# Install the xz-utils package
RUN apt-get update && apt-get install -y xz-utils

FROM mcr.microsoft.com/devcontainers/base:ubuntu

# Instalar Node.js e npm
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs \
    && npm install -g @nestjs/cli

WORKDIR /workspace
